config/routes.rb
Rails.application.routes.draw do
  resources :pegawais
  resources :golongans
  resources :jabatans
  resources :seksis do
    collection do
      get 'update_seksi'
    end
  end
  resources :bidangs
  resources :ttds
  resources :pendataans do
    collection do
      get 'cetak_sptpd'
      get 'surat_teguran'
      get 'cetak_surat_teguran'
    end
  end
  resources :rekenings do
    collection do 
      get 'update_rekening'
    end 
  end
  resources :pendaftarans do
    collection do
      get 'daftar_wajib_pajak'
      match 'cetak_npwpd', via: [:get, :post]
      match 'cetak_kartu_data', via: [:get, :post]
    end
  end
  resources :usahas
  resources :wilayahs, only: [:show, :update, :edit, :create]
  devise_for :users
  resources :kelurahans do
    collection do 
      get 'update_kelurahan'
    end 
  end
  resources :kecamatans

  get 'home/index'

  get 'penyetoran/index'
  get 'penyetoran/proses'
  get 'penyetoran/list'
  match 'penyetoran/cetak_sts', via: [:get, :post]
  get 'penyetoran/cetak_tanda_bukti'

  match 'penetapan/index', via: [:get, :post]
  post 'penetapan/tetapkan'
  get 'penetapan/proses'
  get 'penetapan/list'
  match 'penetapan/cetak_skp', via: [:get, :post]
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wilayah.rb
class Wilayah < ApplicationRecord
    # #slugger
    # extend FriendlyId
    # friendly_id :nama_wilayah, use: :slugged

    #Validasi nama wilayah
    validates :nama_wilayah, :jenis_wilayah, :pemimpin, :ibu_kota, :nama_badan, :alamat_badan, :singkatan, presence: true

end

app/controllers/wilayahs_controller.rb
class WilayahsController < ApplicationController
  before_action :set_wilayah, only: [:show, :edit, :update, :destroy]

  # GET /wilayahs
  # GET /wilayahs.json
  # def index
  #   @wilayahs = Wilayah.all
  # end

  # GET /wilayahs/1
  # GET /wilayahs/1.json
  def show
    redirect_to controller: 'wilayahs', action: 'edit', id: 1
  end

  # GET /wilayahs/new
  # def new
  #   @wilayah = Wilayah.new
  # end

  # GET /wilayahs/1/edit
  def edit
    if @wilayah == nil
      @wilayah = Wilayah.new
    end
  end

  # POST /wilayahs
  # POST /wilayahs.json
  def create
    @wilayah = Wilayah.new(wilayah_params)

    respond_to do |format|
      if @wilayah.save
        format.html { redirect_to @wilayah, notice: 'Wilayah berhasil tersimpan.' }
        format.json { render :show, status: :created, location: @wilayah }
      else
        format.html { render :new }
        format.json { render json: @wilayah.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wilayahs/1
  # PATCH/PUT /wilayahs/1.json
  def update
    respond_to do |format|
      if @wilayah.update(wilayah_params)
        format.html { redirect_to @wilayah, notice: 'Wilayah Berhasil Tersimpan.' }
        format.json { render :show, status: :ok, location: @wilayah }
      else
        format.html { render :edit }
        format.json { render json: @wilayah.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wilayahs/1
  # DELETE /wilayahs/1.json
  # def destroy
  #   @wilayah.destroy
  #   respond_to do |format|
  #     format.html { redirect_to wilayahs_url, notice: 'Wilayah was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wilayah
      @wilayah = Wilayah.first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wilayah_params
      params.require(:wilayah).permit(:nama_wilayah, :jenis_wilayah, :pemimpin, :ibu_kota, :nama_badan, :alamat_badan, :telp_badan, :fax, :singkatan, :kode_pos)
    end
end

app/views/wilayahs/_form.html.erb
<div class="row">
  <div class="col-xs-12">
  <%= form_for(wilayah, :html => {:class => "form-vertical", :role => "form"}) do |f| %>
  <%= render 'shared/error', error_form: wilayah %>

<div class="row">
 <div class="col-md-4">
  <div class="field">
      <div class="form-group">
          <%= f.label :nama_wilayah %>
            <%= f.text_field :nama_wilayah, class: "form-control", validate: true %>
        </div>
  </div>
</div>

 <div class="col-md-4">
  <div class="field">
    <div class="form-group">
    <%= f.label :jenis_wilayah %>
    <%= f.text_field :jenis_wilayah, class: "form-control", validate: true %>
  </div>
  </div>
  </div>

<div class="col-md-4">
  <div class="field">
  <div class="form-group">
    <%= f.label :pemimpin %>
    <%= f.text_field :pemimpin, class: "form-control", validate: true %>
     </div>
  </div>
  </div>
   </div>


<div class="row">

<div class="col-md-8">
  <div class="field">
  <div class="form-group">
    <%= f.label :nama_badan %>
    <%= f.text_field :nama_badan, class: "form-control", validate: true %>
     </div>
  </div>
</div>

<div class="col-md-4">
  <div class="field">
  <div class="form-group">
    <%= f.label :singkatan %>
    <%= f.text_field :singkatan, class: "form-control", validate: true %>
     </div>
  </div>
 </div>
   </div>

   <div class="row">

<div class="col-md-4">
  <div class="field">
  <div class="form-group">
    <%= f.label :ibu_kota %>
    <%= f.text_field :ibu_kota, class: "form-control", validate: true %>
     </div>
  </div>
  </div>
<div class="col-md-4">
  <div class="field">
  <div class="form-group">
    <%= f.label :telp_badan %>
    <%= f.text_field :telp_badan, class: "form-control", validate: true %>
     </div>
  </div>
  </div>

<div class="col-md-4">
  <div class="field">
  <div class="form-group">
    <%= f.label :fax %>
    <%= f.text_field :fax, class: "form-control", validate: true %>
     </div>
  </div>
</div>
   </div>

<div class="row">
  <div class="col-md-8">
  <div class="field">
  <div class="form-group">
    <%= f.label :alamat_badan %>
    <%= f.text_area :alamat_badan, class: "form-control", validate: true %>
     </div>
  </div>
   </div>
   <div class="col-md-4">
  <div class="field">
  <div class="form-group">
    <%= f.label :kode_pos %>
    <%= f.text_field :kode_pos, class: "form-control", validate: true %>
     </div>
  </div>
 </div>
  </div>

 <div class="clearfix form-actions">
        <div class="col-md-offset-3 col-md-9">
        <%= button_tag(type: 'submit', class: "btn btn-info") do %>
          <i class="ace-icon fa fa-check bigger-110"></i> Simpan
        <% end %>
      </div>
    </div>
<% end %>
</div>
</div>

app/views/wilayahs/edit.html.erb
<div class="page-header">
    <h1>Wilayah
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Edit
        </small>
    </h1>
</div>

<%= render 'form', wilayah: @wilayah %>

app/views/wilayahs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wilayahs</h1>

<table>
  <thead>
    <tr>
      <th>Nama wilayah</th>
      <th>Jenis wilayah</th>
      <th>Pemimpin</th>
      <th>Ibu kota</th>
      <th>Nama badan</th>
      <th>Alamat badan</th>
      <th>Telp badan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wilayahs.each do |wilayah| %>
      <tr>
        <td><%= wilayah.nama_wilayah %></td>
        <td><%= wilayah.jenis_wilayah %></td>
        <td><%= wilayah.pemimpin %></td>
        <td><%= wilayah.ibu_kota %></td>
        <td><%= wilayah.nama_badan %></td>
        <td><%= wilayah.alamat_badan %></td>
        <td><%= wilayah.telp_badan %></td>
        <td><%= link_to 'Show', wilayah %></td>
        <td><%= link_to 'Edit', edit_wilayah_path(wilayah) %></td>
        <td><%= link_to 'Destroy', wilayah, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wilayah', new_wilayah_path %>

app/views/wilayahs/new.html.erb
<h1>New Wilayah</h1>

<%= render 'form', wilayah: @wilayah %>

<%= link_to 'Back', wilayahs_path %>

app/views/wilayahs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama wilayah:</strong>
  <%= @wilayah.nama_wilayah %>
</p>

<p>
  <strong>Jenis wilayah:</strong>
  <%= @wilayah.jenis_wilayah %>
</p>

<p>
  <strong>Pemimpin:</strong>
  <%= @wilayah.pemimpin %>
</p>

<p>
  <strong>Ibu kota:</strong>
  <%= @wilayah.ibu_kota %>
</p>

<p>
  <strong>Nama badan:</strong>
  <%= @wilayah.nama_badan %>
</p>

<p>
  <strong>Alamat badan:</strong>
  <%= @wilayah.alamat_badan %>
</p>

<p>
  <strong>Telp badan:</strong>
  <%= @wilayah.telp_badan %>
</p>

<%= link_to 'Edit', edit_wilayah_path(@wilayah) %> |
<%= link_to 'Back', wilayahs_path %>