config/routes.rb
Rails.application.routes.draw do
  resources :pegawais
  resources :golongans
  resources :jabatans
  resources :seksis do
    collection do
      get 'update_seksi'
    end
  end
  resources :bidangs
  resources :ttds
  resources :pendataans do
    collection do
      get 'cetak_sptpd'
      get 'surat_teguran'
      get 'cetak_surat_teguran'
    end
  end
  resources :rekenings do
    collection do 
      get 'update_rekening'
    end 
  end
  resources :pendaftarans do
    collection do
      get 'daftar_wajib_pajak'
      match 'cetak_npwpd', via: [:get, :post]
      match 'cetak_kartu_data', via: [:get, :post]
    end
  end
  resources :usahas
  resources :wilayahs, only: [:show, :update, :edit, :create]
  devise_for :users
  resources :kelurahans do
    collection do 
      get 'update_kelurahan'
    end 
  end
  resources :kecamatans

  get 'home/index'

  get 'penyetoran/index'
  get 'penyetoran/proses'
  get 'penyetoran/list'
  match 'penyetoran/cetak_sts', via: [:get, :post]
  get 'penyetoran/cetak_tanda_bukti'

  match 'penetapan/index', via: [:get, :post]
  post 'penetapan/tetapkan'
  get 'penetapan/proses'
  get 'penetapan/list'
  match 'penetapan/cetak_skp', via: [:get, :post]
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pendaftaran.rb
class Pendaftaran < ApplicationRecord
    include Auditable
    acts_as_paranoid
    belongs_to :kecamatan
    belongs_to :kelurahan
    belongs_to :usaha
    has_many :pendataan
    #Validasi
    validates :nama_usaha, :npwp, :alamat_usaha, :kecamatan_id, :kelurahan_id, :nama_pemilik, :alamat_pemilik, :npwpd, :tgl_npwpd, :usaha_id, :no_reg_pendaftaran, :tgl_npwpd, :tgl_daftar, presence: true
    validates :npwpd, :no_pendaftaran, :no_reg_pendaftaran, :npwpd, uniqueness: true

    enum status: { aktif: 0, tidak_aktif: 1 }
    
    before_save :default_values

    #slugger
    extend FriendlyId
    friendly_id :nama_usaha, use: :slugged

    #scope untuk filter like
    scope :like, ->(args) { where("trim(upper(no_pendaftaran)) like trim(upper('%#{args}%')) or trim(upper(npwpd)) like trim(upper('%#{args}%')) or trim(upper(nama_usaha)) like trim(upper('%#{args}%')) or trim(upper(nama_pemilik)) like trim(upper('%#{args}%'))")}

    GOLONGAN = [["1", "1"], ["2", "2"]]

    # before_create do
    #     self.tgl_daftar = Date.today unless self.day
    # end
    def npwpd_nama_usaha
        "#{npwpd} - #{nama_usaha}"
    end

    def npwp_nama_usaha
        "#{npwp} - #{nama_usaha}"
    end


    def default_values
        self.status ||= 0
    end

end

app/controllers/pendaftarans_controller.rb
class PendaftaransController < ApplicationController
  before_action :set_pendaftaran, only: [:show, :edit, :update, :destroy]
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper
  add_breadcrumb '<i class="ace-icon fa fa-home home-icon"></i> Home'.html_safe, :root_path
  add_breadcrumb 'Pendaftaran'.html_safe, :pendaftarans_path
  include ApplicationHelper

  # GET /pendaftarans
  # GET /pendaftarans.json
  def index
    pendaftaran_scope = Pendaftaran.includes(:kecamatan, :kelurahan).all
    if params[:filter_date].present?
      date = params[:filter_date].split('s/d')
      pendaftaran_scope = pendaftaran_scope.where("tgl_daftar between '" + DateTime.parse(date[0]).strftime("%Y/%m/%d") + "' and '" + DateTime.parse(date[1]).strftime("%Y/%m/%d") + "'")
    end
    pendaftaran_scope = pendaftaran_scope.where("kecamatan_id= " + params[:filter_kecamatan]) if params[:filter_kecamatan].present?
    pendaftaran_scope = pendaftaran_scope.like(params[:filter]) if params[:filter] != ''
    @pendaftaran = smart_listing_create(:pendaftarans, pendaftaran_scope, partial: "pendaftarans/listing", default_sort: {created_at: "desc"})
  end

  # GET /pendaftarans/1
  # GET /pendaftarans/1.json
  def show
    add_breadcrumb @pendaftaran.npwpd
  end

  # GET /pendaftarans/new
  def new
    add_breadcrumb 'Buat Baru'
    @pendaftaran = Pendaftaran.new
    @pendaftaran.no_pendaftaran = generate_no_pendaftaran
    @pendaftaran.no_reg_pendaftaran = generate_no_pendaftaran + '/' + Date.today.year.to_s  
  end

  # GET /pendaftarans/1/edit
  def edit
    add_breadcrumb 'Edit : ' + @pendaftaran.npwpd
    @pendaftaran.tgl_npwpd = @pendaftaran.tgl_npwpd.strftime('%d-%m-%Y')
    @pendaftaran.tgl_daftar = @pendaftaran.tgl_daftar.strftime('%d-%m-%Y')
  end

  # POST /pendaftarans
  # POST /pendaftarans.json
  def create
    @pendaftaran = Pendaftaran.new(pendaftaran_params)
    no_pendaftaran = generate_no_pendaftaran
    npwpd = @pendaftaran.npwpd
    @pendaftaran.no_pendaftaran = no_pendaftaran
    @pendaftaran.no_reg_pendaftaran = no_pendaftaran + '/' + Date.today.year.to_s
    @pendaftaran.npwpd = npwpd[0..3] + no_pendaftaran + '.' + Kecamatan.find(@pendaftaran.kecamatan_id).kode + '.' + Kelurahan.find(@pendaftaran.kelurahan_id).kode
    respond_to do |format|
      if @pendaftaran.save
        format.html { redirect_to @pendaftaran, notice: 'Pendaftaran berhasil tersimpan' }
        format.json { render :show, status: :created, location: @pendaftaran }
      else
        format.html { render :new }
        format.json { render json: @pendaftaran.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pendaftarans/1
  # PATCH/PUT /pendaftarans/1.json
  def update
    respond_to do |format|
      if @pendaftaran.update(pendaftaran_params)
        format.html { redirect_to @pendaftaran, notice: 'Pendaftaran berhasil tersimpan' }
        format.json { render :show, status: :ok, location: @pendaftaran }
      else
        format.html { render :edit }
        format.json { render json: @pendaftaran.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pendaftarans/1
  # DELETE /pendaftarans/1.json
  def destroy
    @pendaftaran.destroy
    respond_to do |format|
      format.html { redirect_to pendaftarans_url, notice: 'Pendaftaran berhasil dihapus' }
      format.json { head :no_content }
    end
  end

  def daftar_wajib_pajak
    add_breadcrumb 'Cetak Daftar Wajib Pajak'
    respond_to do |format|
        format.html
        format.pdf do
          pendaftaran_scope = Pendaftaran.all
          judul = "Daftar Wajib Pajak "
          if params[:filter_date].present?
            judul += params[:filter_date]
            date = params[:filter_date].split('s/d')
            pendaftaran_scope = pendaftaran_scope.where("tgl_daftar between '" + DateTime.parse(date[0]).strftime("%Y/%m/%d") + "' and '" + DateTime.parse(date[1]).strftime("%Y/%m/%d") + "'")
          end
          if params[:filter_kecamatan].present?
            judul += ' ' + Kecamatan.find(params[:filter_kecamatan]).nama
            pendaftaran_scope = pendaftaran_scope.where("kecamatan_id= " + params[:filter_kecamatan])
          end
          pendaftaran_scope = pendaftaran_scope.where("status= ?", Pendaftaran.statuses[params[:status]]) if params[:status].present?
          @pendaftaran = pendaftaran_scope
          @wilayah = Wilayah.first
          @tanggal = params[:filter_date]
          render pdf: judul,
                  disposition: 'attachment',
                  page_size: 'Legal'
        end
    end
  end

  def cetak_npwpd
    add_breadcrumb 'Cetak Kartu NPWPD'
    respond_to do |format|
        format.html
        format.pdf do
          pendaftaran_scope = Pendaftaran.all
          judul = "NPWPD "
          if params[:filter_kecamatan].present?
            judul += ' ' + Kecamatan.find(params[:filter_kecamatan]).nama
            pendaftaran_scope = pendaftaran_scope.where("kecamatan_id= " + params[:filter_kecamatan])
          end
          if params[:no_pendaftaran].present? and params[:no_pendaftaran2].present?
            pendaftaran_scope = pendaftaran_scope.where("no_pendaftaran::int between '" + params[:no_pendaftaran] + "'::int and '" + params[:no_pendaftaran2] + "'::int")
            judul += ' No Pendaftaran' + params[:no_pendaftaran].to_s + ' s/d ' + params[:no_pendaftaran2]
          elsif params[:no_pendaftaran].present? and !params[:no_pendaftaran2].present?
            pendaftaran_scope = pendaftaran_scope.where("no_pendaftaran::int = '" + params[:no_pendaftaran] + "'::int")
            judul += ' No Pendaftaran' + params[:no_pendaftaran].to_s
          elsif !params[:no_pendaftaran].present? and params[:no_pendaftaran2].present?
            pendaftaran_scope = pendaftaran_scope.where("no_pendaftaran::int = '" + params[:no_pendaftaran2] + "'::int")
            judul += ' No Pendaftaran' + params[:no_pendaftaran2]
          end
          @pendaftaran = pendaftaran_scope
          @wilayah = Wilayah.first
          render pdf: judul,
                  margin:  {
                        top: 0,
                        bottom: 0,
                        left: 0,
                        right: 0
                    },
                  disposition: 'attachment',
                  page_height: '2.20472in', 
                  page_width: '3.50394in'
        end
    end
  end

  def cetak_kartu_data
    add_breadcrumb 'Cetak Kartu Data'
    respond_to do |format|
        format.html
        format.pdf do
          pendaftaran_scope = Pendataan.select('tahun_spt, pendaftaran_id, rekening_id').distinct.joins(:rekening, :pendaftaran).all
          judul = "Kartu Data "
          if params[:filter_tahun_rekening].present?
            judul += ' Tahun ' + params[:filter_tahun_rekening].to_s
            pendaftaran_scope = pendaftaran_scope.where("rekenings.tahun= " + params[:filter_tahun_rekening])
          end
          if params[:filter_induk_rekening].present?
            judul += ' Rekening ' + Kecamatan.find_by_kode(params[:filter_induk_rekening]).nama_rekening
            pendaftaran_scope = pendaftaran_scope.where("rekenings.kode= '" + params[:filter_induk_rekening] + "'")
          end
          if params[:no_pendaftaran].present? and params[:no_pendaftaran2].present?
            pendaftaran_scope = pendaftaran_scope.where("no_pendaftaran::int between '" + params[:no_pendaftaran] + "'::int and '" + params[:no_pendaftaran2] + "'::int")
            judul += ' No Pendaftaran' + params[:no_pendaftaran].to_s + ' s/d ' + params[:no_pendaftaran2]
          elsif params[:no_pendaftaran].present? and !params[:no_pendaftaran2].present?
            pendaftaran_scope = pendaftaran_scope.where("no_pendaftaran::int = '" + params[:no_pendaftaran] + "'::int")
            judul += ' No Pendaftaran' + params[:no_pendaftaran].to_s
          elsif !params[:no_pendaftaran].present? and params[:no_pendaftaran2].present?
            pendaftaran_scope = pendaftaran_scope.where("no_pendaftaran::int = '" + params[:no_pendaftaran2] + "'::int")
            judul += ' No Pendaftaran' + params[:no_pendaftaran2]
          end
          @pendaftaran = pendaftaran_scope
          @wilayah = Wilayah.first
          render pdf: judul,
                  margin:  {
                        top: 10,
                        bottom: 10,
                        left: 10,
                        right: 10
                    },
                  disposition: 'attachment', 
                  page_size: 'Legal'
        end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pendaftaran
      @pendaftaran = Pendaftaran.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pendaftaran_params
      params.require(:pendaftaran).permit(:no_pendaftaran, :no_pendaftaran2, :nama_usaha, :alamat_usaha, :kecamatan_id, :kelurahan_id, :no_telp_usaha, :nama_pemilik, :alamat_pemilik, :no_telp_pemilik, :npwpd, :tgl_npwpd, :usaha_id, :filter, :no_reg_pendaftaran, :tgl_daftar, :filter_date, :filter, :filter_kecamatan, :status, :filter_tahun_rekening, :filter_induk_rekening, :npwp)
    end
end

app/views/pendaftarans/_listing.html.erb
<% unless smart_listing.empty? %>
<div class="table-container">
  <table class="table table-striped table-bordered">
    <thead>
      <tr role="row">
        <th class="sorting"><%= smart_listing.sortable "No. Pendaftaran", :no_pendaftaran %></th>
        <th class="sorting"><%= smart_listing.sortable "NPWP", :npwp %></th>
        <th class="sorting"><%= smart_listing.sortable "Tgl. Daftar", :tgl_daftar %></th>
        <th class="sorting"><%= smart_listing.sortable "Nama Usaha", :nama_usaha %></th>
        <th class="sorting"><%= smart_listing.sortable "Nama Pemilik", :nama_pemilik %></th>
        <th class="sorting"><%= smart_listing.sortable "Kecamatan", :kecamatan_id %></th>
        <th class="sorting">Status</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% 
          counting = 1
      %>
      <% smart_listing.collection.each do |pendaftaran| %>
              <% if counting.odd? %>
                  <tr role="row" class="odd">
              <% else %>
                <tr role="row" class="even">
              <% end %>
          <td><%= pendaftaran.no_pendaftaran %></td>
          <td><%= pendaftaran.npwp %></td>
          <td><%= pendaftaran.tgl_daftar.strftime('%d-%m-%Y') %></td>
          <td><%= pendaftaran.nama_usaha %></td>
          <td><%= pendaftaran.nama_pemilik %></td>
          <td><%= pendaftaran.kecamatan.nama %></td>
          <% if pendaftaran.aktif? %>
            <td><span class="label label-sm label-success"><%= pendaftaran.status %></span></td>
          <% else %>
            <td><span class="label label-sm label-danger arrowed-in"><%= pendaftaran.status %></span></td>
          <% end %>
          <td>
              <div class="action-buttons">
                  <%= link_to(raw('<i class="ace-icon fa fa-search-plus bigger-130"></i>'), pendaftaran, class:"blue") %>
                  <%= link_to(raw('<i class="ace-icon fa fa-pencil bigger-130"></i>'), edit_pendaftaran_path(pendaftaran), class:"green") %>
                  <%= link_to(raw('<i class="ace-icon fa fa-trash-o bigger-130"></i>'), pendaftaran, method: :delete, data: { confirm: 'Anda yakin?' }, class:"red") %>
              </div>
          </td>
        </tr>
        <% counting += 1 %>
      <% end %>
    </tbody>
  </table>
</div>
<%= smart_listing.paginate  %>
<% else %>
<p> Data tidak ditemukan </p>
<% end %>

app/views/pendaftarans/cetak_kartu_data.html.erb
<div class="page-header">
    <h1>Pendaftaran
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Cetak Kartu Data
        </small>
    </h1>
</div>
<div class="row">
  <div class="col-xs-12">
		<%= form_tag cetak_kartu_data_pendaftarans_path(:format => 'pdf'), :method => :post, :class => "form-horizontal", :role => "form" do %>
      <div class="field">
        <div class="form-group">
          <%= label_tag :tahun, nil, class: "col-sm-2 control-label no-padding-right" %>
					<div class="col-sm-4">
						<%= select_tag(:filter_tahun_rekening, options_from_collection_for_select(Rekening.select(:tahun).distinct, :tahun, :tahun), {prompt: ' -- Pilih Tahun Pajak -- ', class: "chosen-select  form-control"}) %>
					</div>
				</div>
			</div>
      <div class="field">
				<div class="form-group">
          <%= label_tag :rekening, nil, class: "col-sm-2 control-label no-padding-right" %>
					<div class="col-sm-4">
						<%= select_tag(:filter_induk_rekening, options_from_collection_for_select(Rekening.where("jenis_kode='000' and turunan_kode='000'"), :id, :nama_rekening), {prompt: ' -- Pilih induk Rekening -- ', class: "chosen-select  form-control"}) %>
					</div>
        </div>
      </div>
      <div class="field">
        <div class="form-group">
          <%= label_tag :tanggal_daftar, 'No Pendaftaran', class: "col-sm-2 control-label no-padding-right" %>
          <div class="col-sm-4">
            <div class='input-group'>
								<%= text_field_tag :no_pendaftaran, '', class: "form-control only_allow_number", autocomplete: :on %>
                <span class="input-group-addon">
                  s/d
								</span>
                <%= text_field_tag :no_pendaftaran2, '', class: "form-control only_allow_number", autocomplete: :on %>
            </div>
          </div>
        </div>
      </div>
			<div class="clearfix form-actions">
        <div class="col-sm-offset-2 col-sm-10">
          <%= button_tag(type: 'submit', class: "btn btn-info") do %>
            <i class="ace-icon fa fa-print bigger-110"></i> Cetak
          <% end %>
        </div>
      </div>
		<% end %>
	</div>
</div>

app/views/pendaftarans/cetak_npwpd.html.erb
<div class="page-header">
    <h1>Pendaftaran
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Cetak Kartu NPWPD
        </small>
    </h1>
</div>
<div class="row">
  <div class="col-xs-12">
		<%= form_tag cetak_npwpd_pendaftarans_path(:format => 'pdf'), :method => :post, :class => "form-horizontal", :role => "form" do %>
      <div class="field">
        <div class="form-group">
          <%= label_tag :kecamatan, nil, class: "col-sm-2 control-label no-padding-right" %>
          <div class="col-sm-4">
            <%= select_tag(:filter_kecamatan, options_from_collection_for_select(Kecamatan.all, :id, :kode_dan_kecamatan), {prompt: ' -- Pilih Kecamatan -- ', class: "chosen-select  form-control"}) %>
          </div>
        </div>
      </div>
      <div class="field">
        <div class="form-group">
          <%= label_tag :tanggal_daftar, 'No Pendaftaran', class: "col-sm-2 control-label no-padding-right" %>
          <div class="col-sm-4">
            <div class='input-group'>
								<%= text_field_tag :no_pendaftaran, '', class: "form-control only_allow_number", autocomplete: :on %>
                <span class="input-group-addon">
                  s/d
								</span>
                <%= text_field_tag :no_pendaftaran2, '', class: "form-control only_allow_number", autocomplete: :on %>
            </div>
          </div>
        </div>
      </div>
			<div class="clearfix form-actions">
        <div class="col-sm-offset-2 col-sm-10">
          <%= button_tag(type: 'submit', class: "btn btn-info") do %>
            <i class="ace-icon fa fa-print bigger-110"></i> Cetak
          <% end %>
        </div>
      </div>
		<% end %>
	</div>
</div>

app/views/pendaftarans/cetak_npwpd.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <style>
      div.alwaysbreak { page-break-before: always; }
      div.nobreak:before { clear:both; }
      div.nobreak { page-break-inside: avoid; }
    </style>
  </head>
  <body>
    <% @pendaftaran.each do |item| %>
      <div class="alwaysbreak"></div>
      <div style="padding-top:90px;padding-left:110px;padding-right:10px;font-size:12px;">
        <%= item.npwpd %>
      </div>
      <div style="padding-top:10px;padding-left:110px;padding-right:10px;font-size:12px;">
        <%= item.nama_usaha %>
      </div>
      <div style="padding-top:10px;padding-left:110px;padding-right:10px;font-size:12px;">
        <%= item.alamat_usaha %>
      </div>
    <% end %>
  </body>
</html>

app/views/pendaftarans/daftar_wajib_pajak.html.erb
<div class="page-header">
    <h1>Pendaftaran
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Cetak daftar wajib pajak
        </small>
    </h1>
</div>
<div class="row">
  <div class="col-xs-12">
		<%= form_tag daftar_wajib_pajak_pendaftarans_path(:format => 'pdf'), :method => :get, :class => "form-horizontal", :role => "form" do %>
      <div class="field">
        <div class="field">
          <div class="form-group">
            <%= label_tag :status, nil, class: "col-sm-2 control-label no-padding-right" %>
              <div class="col-md-2">
                <%= select_tag(:status, options_for_select(Pendaftaran.statuses.keys.to_a.map { |w| [w.humanize, w] }), {prompt: ' -- Semua -- ', class: "form-control"}) %>
              </div>
            </div>
          </div>
        </div>
      <div class="field">
        <div class="form-group">
          <%= label_tag :kecamatan, nil, class: "col-sm-2 control-label no-padding-right" %>
          <div class="col-sm-4">
            <%= select_tag(:filter_kecamatan, options_from_collection_for_select(Kecamatan.all, :id, :kode_dan_kecamatan), {prompt: ' -- Pilih Kecamatan -- ', class: "chosen-select  form-control"}) %>
          </div>
        </div>
      </div>
      <div class="field">
        <div class="form-group">
          <%= label_tag :tanggal_daftar, nil, class: "col-sm-2 control-label no-padding-right" %>
          <div class="col-sm-4">
            <div class='input-group'>
								<%= text_field_tag :filter_date, '', class: "form-control range-picker", placeholder: "Search by date...", autocomplete: :on %>
                <span class="input-group-addon">
																		<i class="fa fa-calendar bigger-110"></i>
																	</span>
                </div>
          </div>
        </div>
      </div>
			<div class="clearfix form-actions">
        <div class="col-sm-offset-2 col-sm-10">
          <%= button_tag(type: 'submit', class: "btn btn-info") do %>
            <i class="ace-icon fa fa-print bigger-110"></i> Cetak
          <% end %>
        </div>
      </div>
		<% end %>
	</div>
</div>

app/views/pendaftarans/daftar_wajib_pajak.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
  </head>
  <body>
  <table width="100%" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse">
  <tr role="row" style="text-align:center; padding-top:10px;">
	<td style="text-align:center; padding-top:10px;">
	  <p style="font-size:12pt;">DAFTAR WAJIB PAJAK <%= @wilayah.jenis_wilayah.upcase + ' ' + @wilayah.nama_wilayah.upcase %></p>
      <p style="font-size:9pt;"><%= @tanggal %></p>
	</td>
  </tr>
</td>
</table>
<hr>
<div class="container">
  <table width="100%" border="1" cellpadding="0" cellspacing="0" style="border-collapse:collapse;font-size:10pt;" >
    <thead>
      <tr role="row" style="text-align:center; padding-top:10px;">
        <th class="sorting" style="text-align:center; padding:5px;">No</th>
        <th class="sorting" style="text-align:center; padding:5px;">No. Pendaftaran</th>
        <th class="sorting" style="text-align:center; padding:5px;">NPWP</th>
        <th class="sorting" style="text-align:center; padding:5px;">Tgl. Daftar</th>
        <th class="sorting" style="text-align:center; padding:5px;">Nama Usaha</th>
        <th class="sorting" style="text-align:center; padding:5px;">Nama Pemilik</th>
        <th class="sorting" style="text-align:center; padding:5px;">Status</th>
      </tr>
    </thead>

    <tbody>
      <% 
          counting = 1
      %>
      <% @pendaftaran.each do |pendaftaran| %>
              <% if counting.odd? %>
                  <tr role="row" class="odd">
              <% else %>
                <tr role="row" class="even">
              <% end %>
              <td style="text-align:center; padding:5px;"><%= counting %></td>
          <td style="text-align:center; padding:5px;"><%= pendaftaran.no_pendaftaran %></td>
          <td style="text-align:center; padding:5px;"><%= pendaftaran.npwp %></td>
          <td style="text-align:center; padding:5px;"><%= pendaftaran.tgl_daftar.strftime('%d-%m-%Y') %></td>
          <td style="padding:5px;"><%= pendaftaran.nama_usaha %></td>
          <td style="padding:5px;"><%= pendaftaran.nama_pemilik %></td>
          <td style="padding:5px;"><%= pendaftaran.status %></td>
        </tr>
        <% counting += 1 %>
      <% end %>
    </tbody>
  </table>
</div>
  </body>
</html>

app/views/pendaftarans/edit.html.erb
<div class="page-header">
    <h1>Pendaftaran
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Edit
        </small>
    </h1>
</div>
<%= render 'form', pendaftaran: @pendaftaran %>

app/views/pendaftarans/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h3 class="header smaller lighter blue">Index Daftar Pendaftaran</h3>
    <div class="clearfix"></div>
	<div class="row">
		<div class="col-xs-12">
			<div class="pull-right tableTools-container">
				<div class="dt-buttons btn-overlap btn-group">
					<%= link_to(raw('<i class="ace-icon fa fa-plus icon-on-right bigger-110"></i> Tambah Pendaftaran'), new_pendaftaran_path, class: "dt-button buttons-collection buttons-colvis btn btn-success") %>
				</div>
			</div>
		</div>
	</div>
  <div class="table-header"> Tabel Pendaftaran </div>
		<div id="dynamic-table_wrapper" class="dataTables_wrapper form-inline">
			<div class="row">
				<%= smart_listing_controls_for(:pendaftarans, {class: "form-inline text-right"}) do %>
				<div class="col-xs-12 col-sm-12 col-md-12">
					<div class='input-group'>
						<%= select_tag(:filter_kecamatan, options_from_collection_for_select(Kecamatan.all, :id, :kode_dan_kecamatan), {prompt: ' -- Pilih Kecamatan -- ', class: "chosen-select  form-control", onchange:"$('.smart-listing-controls').submit();"}) %>
					</div>
						<div class='input-group'>
						<%= text_field_tag :filter_date, '', class: "search form-control range-picker", placeholder: "Search by date...", autocomplete: :on %>
                <span class="input-group-addon">
																		<i class="fa fa-calendar bigger-110"></i>
																	</span>
                </div>
					<div class="input-group">
						<%= text_field_tag :filter, '', class: "search form-control", placeholder: "Search...", autocomplete: :on, onchange:"$('.smart-listing-controls').submit();" %>
						<div class="input-group-btn">
							<button class="btn btn-primary no-border btn-sm" type="submit">
								<i class="ace-icon fa fa-search icon-on-right bigger-110"></i>
							</button>
						</div>
					</div>
				</div>
				<% end %>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12">
					<%= smart_listing_render(:pendaftarans) %>
				</div>
			</div>
		</div>
	</div>
  </div>
</div>

app/views/pendaftarans/index.js.erb
<%= smart_listing_update :pendaftarans %>

app/views/pendaftarans/new.html.erb
<div class="page-header">
    <h1>Pendaftaran
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Buat baru
        </small>
    </h1>
</div>
<%= render 'form', pendaftaran: @pendaftaran %>