config/routes.rb
Rails.application.routes.draw do
  resources :pegawais
  resources :golongans
  resources :jabatans
  resources :seksis do
    collection do
      get 'update_seksi'
    end
  end
  resources :bidangs
  resources :ttds
  resources :pendataans do
    collection do
      get 'cetak_sptpd'
      get 'surat_teguran'
      get 'cetak_surat_teguran'
    end
  end
  resources :rekenings do
    collection do 
      get 'update_rekening'
    end 
  end
  resources :pendaftarans do
    collection do
      get 'daftar_wajib_pajak'
      match 'cetak_npwpd', via: [:get, :post]
      match 'cetak_kartu_data', via: [:get, :post]
    end
  end
  resources :usahas
  resources :wilayahs, only: [:show, :update, :edit, :create]
  devise_for :users
  resources :kelurahans do
    collection do 
      get 'update_kelurahan'
    end 
  end
  resources :kecamatans

  get 'home/index'

  get 'penyetoran/index'
  get 'penyetoran/proses'
  get 'penyetoran/list'
  match 'penyetoran/cetak_sts', via: [:get, :post]
  get 'penyetoran/cetak_tanda_bukti'

  match 'penetapan/index', via: [:get, :post]
  post 'penetapan/tetapkan'
  get 'penetapan/proses'
  get 'penetapan/list'
  match 'penetapan/cetak_skp', via: [:get, :post]
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pendataan.rb
class Pendataan < ApplicationRecord
    extend FriendlyId

    enum status: {sptpd:0, skpd:1, skpdkb:2, skpdn:3, belum_penetapan:4}
    
    friendly_id :no_pendataan, use: :slugged
    belongs_to :pendaftaran
    belongs_to :rekening
    has_many :penetapan

    validates :tgl_data, :tahun_spt, :pendaftaran_id, :rekening_id, :periode_awal, :periode_akhir, :jumlah_pajak, :no_pendataan, presence: true
    validates :no_pendataan, uniqueness: true
    validate :massa_pajak, :on => :create, if: "self.rekening.kode != '1104'" 
    validate :massa_pajak_update, :on => :update, if: "self.rekening.kode != '1104'" 
    validates :pemakaian_daya, :volume_pemakaian, presence: true, if: "self.rekening.kode == '1105'"
    validates :omzet, presence: true, if: "self.rekening.kode != '1105' and self.rekening.kode != '1111' and self.rekening.kode != '1104' and self.rekening.kode != '1108'"
    validates :jumlah_volume, presence: true, if: "self.rekening.kode == '1111'"
    validates :jumlah_reklame, :jumlah_hari_reklame, :panjang_reklame, :lebar_reklame, :nilai_lokasi_reklame, :sudut_pandang_reklame, presence: true, if: "self.rekening.kode == '1104'"
    validates :npa, presence: true, if: "self.rekening.kode == '1108'"
    acts_as_paranoid

    attr_accessor :tarif_persen, :tarif_rupiah, :kode_rekening

    scope :like, ->(args) { where("pendataans.tahun_spt::text= '#{args}' or pendataans.no_pendataan= '#{args}' or trim(upper(rekenings.nama_rekening)) like trim(upper('%#{args}%')) or trim(upper(pendaftarans.npwpd)) like trim(upper('%#{args}%')) or trim(upper(pendaftarans.nama_usaha)) like trim(upper('%#{args}%'))")}
    def massa_pajak
        if self.tahun_spt.present? and self.rekening_id.present? and self.periode_awal.present? 
            @pendataan = Pendataan.where("pendaftaran_id=" + self.pendaftaran_id.to_s + " and tahun_spt=" + self.tahun_spt.to_s + " and rekening_id=" + self.rekening_id.to_s + " and Extract(month from periode_awal)=Extract(month from '" + self.periode_awal.to_s + "'::date) and Extract(year from periode_awal)=Extract(year from '" + self.periode_awal.to_s + "'::date)")
            if @pendataan.present?
                errors.add(:periode_awal, " masa pajak yang anda pilih sudah ada.")
            else
                true
            end   
        else
            true
        end
    end

    def massa_pajak_update
        if self.tahun_spt.present? and self.rekening_id.present? and self.periode_awal.present? 
            @pendataan = Pendataan.where("pendaftaran_id=" + self.pendaftaran_id.to_s + " and tahun_spt=" + self.tahun_spt.to_s + " and rekening_id=" + self.rekening_id.to_s + " and Extract(month from periode_awal)=Extract(month from '" + self.periode_awal.to_s + "'::date) and Extract(year from periode_awal)=Extract(year from '" + self.periode_awal.to_s + "'::date) and id !=" + self.id.to_s)
            if @pendataan.present?
                errors.add(:periode_awal, "/ masa pajak yang anda pilih sudah ada.")
            else
                true
            end   
        else
            true
        end
    end

    def jatuh_tempo
        if self.rekening.kode == '1104' or self.rekening.kode == '1108'
            if self.penetapan.last.tgl_tetap.present?
                self.penetapan.last.tgl_tetap + 15.days
            else
                '-'
            end
        else
            if self.periode_awal.day > 1
                DateTime.parse(self.periode_awal.year.to_s + '-' + self.periode_awal.month.to_s + '-15') + 1.months
            else
                self.periode_awal + 14.days + 1.months
            end
        end
    end

    def hitung_denda(tgl_cetak)
        if self.jatuh_tempo <= tgl_cetak
            (((tgl_cetak.year - self.jatuh_tempo.year) * 12) + tgl_cetak.month - self.jatuh_tempo.month + (tgl_cetak.day < self.jatuh_tempo.day ? 0 : 1)) * 0.02 * self.jumlah_pajak
        else
            0
        end
    end 

    LOKASI = [["Kawasan 1", "10"], ["Kawasan 2", "8"], ["Kawasan 3", "6"], ["Kawasan 4", "4"], ["Kawasan 5", "2"]]
    SUDUT_PANDANG = [["> dari 4 arah", "10"], ["4 arah", "8"], ["3 arah", "6"], ["2 arah", "4"], ["1 arah", "2"]]
end

app/controllers/pendataans_controller.rb
class PendataansController < ApplicationController
  before_action :set_pendataan, only: [:show, :edit, :update, :destroy]
  before_action :set_rekening, only: [:show, :edit, :index, :new, :create, :update]
  before_action :set_parameter, only: [:create, :update]
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper
  include ApplicationHelper

  # GET /pendataans
  # GET /pendataans.json
  def index
    pendataans_scope = Pendataan.includes(:rekening, pendaftaran: [:kecamatan, :kelurahan]).joins(:rekening, pendaftaran: [:kecamatan, :kelurahan]).where('rekenings.kode= ?', @rekening.kode)
    pendataans_scope = pendataans_scope.like(params[:filter]) if params[:filter].present?
    if params[:filter_date].present?
      date = params[:filter_date].split('s/d')
      pendataans_scope = pendataans_scope.where("tgl_data between '" + DateTime.parse(date[0]).strftime("%Y/%m/%d") + "' and '" + DateTime.parse(date[1]).strftime("%Y/%m/%d") + "'")
    end
    @pendaftaran = smart_listing_create(:pendataans, pendataans_scope, partial: "pendataans/listing", default_sort: {"pendataans.created_at": "desc"})
  end

  # GET /pendataans/1
  # GET /pendataans/1.json
  def show
    add_breadcrumb @pendataan.no_pendataan
  end

  # GET /pendataans/new
  def new
    add_breadcrumb 'Buat Baru'
    @pendataan = Pendataan.new
    @pendataan.no_pendataan = generate_no_pendataan
  end

  # GET /pendataans/1/edit
  def edit
    redirect_to @pendataan if @pendataan.penetapan.first.no_setor.present?
    add_breadcrumb 'Edit : ' + @pendataan.no_pendataan
    @pendataan.tgl_data = @pendataan.tgl_data.strftime('%d-%m-%Y')
    @pendataan.periode_awal = @pendataan.periode_awal.strftime('%d-%m-%Y')
    @pendataan.periode_akhir = @pendataan.periode_akhir.strftime('%d-%m-%Y')
    @pendataan.tarif_rupiah = @pendataan.rekening.tarif
    @pendataan.tarif_persen = @pendataan.rekening.persen.to_i
  end

  # POST /pendataans
  # POST /pendataans.json
  def create
    @pendataan = Pendataan.new(pendataan_params)
    @pendataan.no_pendataan = generate_no_pendataan
    if @pendataan.kode_rekening == '1104' or @pendataan.kode_rekening == '1108'
      @pendataan.status = 4
    else
      @pendataan.status = 0
    end
    respond_to do |format|
      if @pendataan.save
        Penetapan.create!(
          pendataan_id:@pendataan.id, 
          pemakaian_daya_teliti:@pendataan.pemakaian_daya,
          volume_pemakaian_teliti:@pendataan.volume_pemakaian,
          jumlah_volume_teliti:@pendataan.jumlah_volume,
          pajak_rokok_teliti:@pendataan.pajak_rokok,
          nilai_reklame_teliti:@pendataan.nilai_reklame,
          npa_teliti:@pendataan.npa,
          omzet_teliti:@pendataan.omzet,
          jumlah_pajak_teliti:@pendataan.jumlah_pajak, 
          jumlah_reklame: @pendataan.jumlah_reklame,
          jumlah_hari_reklame: @pendataan.jumlah_hari_reklame, 
          panjang_reklame: @pendataan.panjang_reklame, 
          lebar_reklame: @pendataan.lebar_reklame, 
          nilai_lokasi_reklame: @pendataan.nilai_lokasi_reklame, 
          sudut_pandang_reklame: @pendataan.sudut_pandang_reklame, 
          luas_reklame: @pendataan.luas_reklame, 
          tinggi_reklame: @pendataan.tinggi_reklame
          )
        format.html { redirect_to @pendataan, notice: 'Pendataan berhasil tersimpan.' }
        format.json { render :show, status: :created, location: @pendataan }
      else
        format.html { render :new }
        format.json { render json: @pendataan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pendataans/1
  # PATCH/PUT /pendataans/1.json
  def update
    respond_to do |format|
      if @pendataan.update(pendataan_params)
        format.html { redirect_to @pendataan, notice: 'Pendataan berhasil tersimpan.' }
        format.json { render :show, status: :ok, location: @pendataan }
      else
        format.html { render :edit }
        format.json { render json: @pendataan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pendataans/1
  # DELETE /pendataans/1.json
  def destroy
    @pendataan.destroy
    respond_to do |format|
      format.html { redirect_to pendataans_url, notice: 'Pendataan berhasil terhapus.' }
      format.json { head :no_content }
    end
  end

  def cetak_sptpd
    add_breadcrumb 'Cetak SPTPD'
    @wilayah = Wilayah.first
    @pendataan = Pendataan.find(params[:id])
    @pendataan_sebelumnya = Pendataan.where("pendaftaran_id=" + @pendataan.pendaftaran_id.to_s + " and rekening_id=" + @pendataan.rekening_id.to_s + " and Extract(month from periode_awal)=Extract(month from '" + (@pendataan.periode_awal - 1.month).to_s + "'::date) and Extract(year from periode_awal)=Extract(year from '" + (@pendataan.periode_awal - 1.month).to_s + "'::date)").order('id desc').first
    @rekening_induk = Rekening.where("jenis_kode = '00' and turunan_kode = '00' and kode= '" + @pendataan.rekening.kode + "' and tahun = " + @pendataan.rekening.tahun.to_s).first
    respond_to do |format|
        # format.html
        format.pdf do
          render pdf: 'SPTPD ' + @pendataan.pendaftaran.npwpd + ' ' + I18n.l(@pendataan.periode_awal, format:'%d %B %Y') + ' s/d ' + I18n.l(@pendataan.periode_akhir, format:'%d %B %Y') ,
                 margin:  {
                   top: 5,
                   bottom: 5,
                   left: 5,
                   right: 5
                  },
                disposition: 'attachment'
        end
    end
  end

  def surat_teguran
    add_breadcrumb '<i class="ace-icon fa fa-home home-icon"></i> Home'.html_safe, :root_path
    add_breadcrumb 'Cetak Surat Teguran'
    if params[:tgl_data].present?
      @current_date = params[:tgl_data]
    else
      @current_date = Time.now.strftime('%d-%m-%Y')
    end
    teguran_scope = Pendataan.joins(:rekening, pendaftaran: [:kecamatan, :kelurahan]).all
    session[:kode_rekening] = nil
    teguran_scope = teguran_scope.where("extract(year from ((periode_awal + interval '1' month) + interval '14' day)) = extract(year from to_date('" + @current_date + "', 'DD/MM/YYYY')) and extract(month from ((periode_awal + interval '1' month) + interval '14' day)) = extract(month from to_date('" + @current_date + "', 'DD/MM/YYYY'))")
    teguran_scope = teguran_scope.where("pendataans.tgl_setor is null and pendataans.tgl_tetap is null")
    teguran_scope = teguran_scope.where("tahun_spt = ?", params[:filter_tahun_rekening]) if params[:filter_tahun_rekening].present?
    teguran_scope = teguran_scope.where("case when rekenings.kode = '1104' or rekenings.kode = '1108' then tgl_tetap is not null else 1=1 end")
    teguran_scope = teguran_scope.where("rekenings.kode = ?", params[:filter_induk_rekening]) if params[:filter_induk_rekening].present?
    @pendaftaran = smart_listing_create(:tegurans, teguran_scope, partial: "pendataans/listing_teguran", default_sort: {created_at: "desc"})
  end

  def cetak_surat_teguran
    @pendataan = Pendataan.find(params[:id])
    @wilayah = Wilayah.first
    @tgl_cetak = params[:tgl_cetak]
    @perihal = 'Teguran I'
    @jml_hari = ((@pendataan.periode_awal + 13.days + 1.month) - DateTime.parse(@tgl_cetak)).to_i
    @rekening_induk = Rekening.where("tahun=" + @pendataan.rekening.tahun.to_s + " and kode='" + @pendataan.rekening.kode + "' and jenis_kode='00' and turunan_kode='00'").first
    @ttd = Ttd.find(1)
    respond_to do |format|
        # format.html
        format.pdf do
          render pdf: 'Surat_Teguran_' + @pendataan.no_pendataan.to_s + '_' + @tgl_cetak,
                 margin:  {
                   top: 10,
                   bottom: 10,
                   left: 10,
                   right: 10
                  },
               disposition: 'attachment'
        end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pendataan
      @pendataan = Pendataan.friendly.find(params[:id])
      session[:kode_rekening] = Rekening.find(@pendataan.rekening_id).kode
    end

    def set_rekening
      add_breadcrumb '<i class="ace-icon fa fa-home home-icon"></i> Home'.html_safe, :root_path
      add_breadcrumb 'Pendataan'.html_safe, pendataans_path(kode_rekening: params[:kode_rekening])
      kode_rekening = ''
      if params[:kode_rekening].present?
        session[:kode_rekening] = params[:kode_rekening]
        kode_rekening = params[:kode_rekening]
      else
        if session[:kode_rekening].present?
          kode_rekening = session[:kode_rekening]
        else
          respond_to do |format|
            format.html { redirect_to root_path, notice: 'session anda expired.' }
          end
          return
        end
      end
      @rekening = Rekening.where("kode = '" + kode_rekening + "' and jenis_kode='00' and turunan_kode='00'").last
    end

    def set_parameter
      params[:pendataan][:omzet] = params[:pendataan][:omzet].gsub('.', '').gsub(',', '.') if params[:pendataan][:omzet].present?
      params[:pendataan][:pemakaian_daya] = params[:pendataan][:pemakaian_daya].gsub('.', '').gsub(',', '.') if params[:pendataan][:pemakaian_daya].present?
      params[:pendataan][:volume_pemakaian] = params[:pendataan][:volume_pemakaian].gsub('.', '').gsub(',', '.') if params[:pendataan][:volume_pemakaian].present?
      params[:pendataan][:jumlah_pajak] = params[:pendataan][:jumlah_pajak].gsub('.', '').gsub(',', '.')
      params[:pendataan][:jumlah_volume] = params[:pendataan][:jumlah_volume].gsub('.', '').gsub(',', '.') if params[:pendataan][:jumlah_volume].present?
      params[:pendataan][:nilai_reklame] = params[:pendataan][:nilai_reklame].gsub('.', '').gsub(',', '.') if params[:pendataan][:nilai_reklame].present?
      params[:pendataan][:npa] = params[:pendataan][:npa].gsub('.', '').gsub(',', '.') if params[:pendataan][:npa].present?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pendataan_params

app/views/pendataans/_listing.html.erb
<% unless smart_listing.empty? %>
<div class="table-container">
  <table class="table table-striped table-bordered">
    <thead>
      <tr role="row">
        <th class="sorting">Tahun SPT</th>
        <th class="sorting">No Pendataan</th>
        <th class="sorting">Rekening</th>
        <th class="sorting">NPWP</th>
        <th class="sorting">Nama Usaha</th>
        <th class="sorting">Periode</th>
        <th class="sorting">Jatuh Tempo</th>
        <th class="sorting">Status</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% 
          counting = 1
      %>
      <% smart_listing.collection.each do |pendataan| %>
              <% if counting.odd? %>
                  <tr role="row" class="odd">
              <% else %>
                <tr role="row" class="even">
              <% end %>
          <td><%= pendataan.tahun_spt %></td>
          <td><%= pendataan.no_pendataan %></td>
          <td><%= pendataan.rekening.nama_rekening %></td>
          <td><%= pendataan.pendaftaran.npwp %></td>
          <td><%= pendataan.pendaftaran.nama_usaha %></td>
          <td><%= I18n.l(pendataan.periode_awal, format:'%d %B %Y') + ' s/d ' + I18n.l(pendataan.periode_akhir, format:'%d %B %Y') %></td>
          <td><% if pendataan.jatuh_tempo == '-' %>
            <%= pendataan.jatuh_tempo %>
          <% else %>
            <%= I18n.l(pendataan.jatuh_tempo, format:'%d %B %Y')  %>
          <% end %></td>
          <td><%= pendataan.status %></td>
          <td>
              <div class="action-buttons">
                  <% if pendataan.rekening.kode != '1104' %>
                    <%= link_to(raw('<i class="ace-icon fa fa-print bigger-130"></i>'), cetak_sptpd_pendataans_path(id: pendataan.id, format: 'pdf')) %>
                  <% end %>
                  <%= link_to(raw('<i class="ace-icon fa fa-search-plus bigger-130"></i>'), pendataan, class:"blue") %>
                  <%= link_to(raw('<i class="ace-icon fa fa-pencil bigger-130"></i>'), edit_pendataan_path(pendataan), class:"green") %>
                  <%= link_to(raw('<i class="ace-icon fa fa-trash-o bigger-130"></i>'), pendataan, method: :delete, data: { confirm: 'Anda yakin?' }, class:"red") %>
              </div>
          </td>
        </tr>
        <% counting += 1 %>
      <% end %>
    </tbody>
  </table>
</div>
<%= smart_listing.paginate  %>
<% else %>
<p> Data tidak ditemukan </p>
<% end %>

app/views/pendataans/_listing_teguran.html.erb
<% unless smart_listing.empty? %>
<div class="table-container">
  <table class="table table-striped table-bordered">
    <thead>
      <tr role="row">
        <th class="sorting">Tahun SPT</th>
        <th class="sorting">No Pendataan</th>
        <th class="sorting">Rekening</th>
        <th class="sorting">NPWP</th>
        <th class="sorting">Nama Usaha</th>
        <th class="sorting">Periode</th>
        <th class="sorting">Tgl Jatuh Tempo</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% 
          counting = 1
      %>
      <% smart_listing.collection.each do |pendataan| %>
              <% if counting.odd? %>
                  <tr role="row" class="odd">
              <% else %>
                <tr role="row" class="even">
              <% end %>
          <td><%= pendataan.tahun_spt %></td>
          <td><%= pendataan.no_pendataan %></td>
          <td><%= pendataan.rekening.nama_rekening %></td>
          <td><%= pendataan.pendaftaran.npwp %></td>
          <td><%= pendataan.pendaftaran.nama_usaha %></td>
          <td><%= I18n.l(pendataan.periode_awal, format:'%d %B %Y') + ' s/d ' + I18n.l(pendataan.periode_akhir, format:'%d %B %Y') %></td>
          <td><%= I18n.l(pendataan.jatuh_tempo, format:'%d %B %Y') %></td>
          <td>
              <div class="action-buttons">
                  <%= link_to(raw('<i class="ace-icon fa fa-print bigger-130"></i>'), cetak_surat_teguran_pendataans_path(id: pendataan.id, tgl_cetak: @current_date, format: 'pdf')) %>
              </div>
          </td>
        </tr>
        <% counting += 1 %>
      <% end %>
    </tbody>
  </table>
</div>
<%= smart_listing.paginate  %>
<% else %>
<p> Data tidak ditemukan </p>
<% end %>

app/views/pendataans/edit.html.erb
<div class="page-header">
    <h1>Pendaftaran <%= @rekening.nama_rekening.split.map(&:capitalize).join(' ') %>
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Edit : <%= @pendataan.no_pendataan %>
        </small>
    </h1>
</div>
<%= render 'form', pendataan: @pendataan, rekening: @rekening %>

app/views/pendataans/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h3 class="header smaller lighter blue">Index Daftar Pendataan <%= @rekening.nama_rekening.split.map(&:capitalize).join(' ') %></h3>
    <div class="clearfix"></div>
	<div class="row">
		<div class="col-xs-12">
			<div class="pull-right tableTools-container">
				<div class="dt-buttons btn-overlap btn-group">
					<%= link_to(raw('<i class="ace-icon fa fa-plus icon-on-right bigger-110"></i> Tambah Pendataan'), new_pendataan_path(:kode_rekening => @rekening.kode), class: "dt-button buttons-collection buttons-colvis btn btn-success") %>
				</div>
			</div>
		</div>
	</div>
  <div class="table-header"> Tabel Pendataan </div>
		<div id="dynamic-table_wrapper" class="dataTables_wrapper form-inline">
			<div class="row">
				<%= smart_listing_controls_for(:pendataans, {class: "form-inline text-right"}) do %>
				<div class="col-xs-12 col-sm-12 col-md-12">
					<div class='input-group'>
						<%= text_field_tag :filter_date, '', class: "search form-control range-picker", placeholder: "Search by date...", autocomplete: :on %>
                <span class="input-group-addon">
									<i class="fa fa-calendar bigger-110"></i>
																	</span>
                </div>
					<div class="input-group">
						<%= text_field_tag :filter, '', class: "search form-control", placeholder: "Search...", autocomplete: :on, onchange:"$('.smart-listing-controls').submit();" %>
						<div class="input-group-btn">
							<button class="btn btn-primary no-border btn-sm" type="submit">
								<i class="ace-icon fa fa-search icon-on-right bigger-110"></i>
							</button>
						</div>
					</div>
				</div>
				<% end %>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12">
					<%= smart_listing_render(:pendataans) %>
				</div>
			</div>
		</div>
	</div>
  </div>
</div>

app/views/pendataans/new.html.erb
<div class="page-header">
    <h1>Pendaftaran <%= @rekening.nama_rekening.split.map(&:capitalize).join(' ') %>
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Buat baru
        </small>
    </h1>
</div>
<%= render 'form', pendataan: @pendataan, rekening: @rekening %>

app/views/pendataans/surat_teguran.html.erb
<div class="page-header">
    <h1>Pendaftaran
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Cetak Surat Teguran
        </small>
    </h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <%= smart_listing_controls_for(:tegurans, {class:"form-vertical", :role => "form"}) do %>
            <div class="col-xs-12">
                <div class="col-md-2">
                    <div class="field">
                        <div class="form-group">
                            <%= label_tag :tanggal_cetak %>
                            <div class='input-group'>
                                <%= text_field_tag :tgl_data, @current_date, {class: "form-control date-picker", 'data-date-format'=>"dd-mm-yyyy"} %>
                                <span class="input-group-addon">
                                    <i class="fa fa-calendar bigger-110"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="field">
                        <div class="form-group">
                            <%= label_tag :jenis_surat %>
                            <%= select_tag(:jenis_surat, options_for_select([['Teguran I', 1],['Teguran II', 2],['Teguran III',3]]), {class: "chosen-select  form-control"}) %>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <div class="col-md-2">
                    <div class="field">
                        <div class="form-group">
                            <%= label_tag :tahun_spt %>
                            <%= select_tag(:filter_tahun_rekening, options_from_collection_for_select(Rekening.select(:tahun).distinct, :tahun, :tahun), {prompt: ' -- Tahun Pajak -- ', class: "chosen-select  form-control"}) %>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="field">
                        <div class="form-group">
                            <%= label_tag :Rekening %>
                            <%= select_tag(:filter_induk_rekening, options_from_collection_for_select(Rekening.where("jenis_kode='000' and turunan_kode='000'"), :id, :nama_rekening), {prompt: ' -- Pilih induk Rekening -- ', class: "chosen-select  form-control"}) %>
                        </div>
                    </div>
                </div>
            </div>
        <div class="col-xs-12">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="widget-box">
                        <div class="widget-header widget-header-flat">
                            <div class="widget-toolbar">
                                <%= link_to(raw('<i class="ace-icon fa fa-search"> Refresh</i>'), 'javascript:void(0)', onclick:"$('.smart-listing-controls').submit();") %>
                            </div>
                        </div>
                        <div class="widget-body">
                            <div class="widget-main">
                                <% end %>
                                <%= smart_listing_render(:tegurans) %>
                             </div>
                        </div>
                     </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pendataans/surat_teguran.js.erb
<%= smart_listing_update :tegurans %>