config/routes.rb
Rails.application.routes.draw do
  resources :pegawais
  resources :golongans
  resources :jabatans
  resources :seksis do
    collection do
      get 'update_seksi'
    end
  end
  resources :bidangs
  resources :ttds
  resources :pendataans do
    collection do
      get 'cetak_sptpd'
      get 'surat_teguran'
      get 'cetak_surat_teguran'
    end
  end
  resources :rekenings do
    collection do 
      get 'update_rekening'
    end 
  end
  resources :pendaftarans do
    collection do
      get 'daftar_wajib_pajak'
      match 'cetak_npwpd', via: [:get, :post]
      match 'cetak_kartu_data', via: [:get, :post]
    end
  end
  resources :usahas
  resources :wilayahs, only: [:show, :update, :edit, :create]
  devise_for :users
  resources :kelurahans do
    collection do 
      get 'update_kelurahan'
    end 
  end
  resources :kecamatans

  get 'home/index'

  get 'penyetoran/index'
  get 'penyetoran/proses'
  get 'penyetoran/list'
  match 'penyetoran/cetak_sts', via: [:get, :post]
  get 'penyetoran/cetak_tanda_bukti'

  match 'penetapan/index', via: [:get, :post]
  post 'penetapan/tetapkan'
  get 'penetapan/proses'
  get 'penetapan/list'
  match 'penetapan/cetak_skp', via: [:get, :post]
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rekening.rb
class Rekening < ApplicationRecord

    has_many :rekening
    validates :tahun, :kode, :jenis_kode, :turunan_kode, :nama_rekening, presence: true
    validates :status, presence: true, if: "self.kode == '1104' and self.jenis_kode != '00' and self.turunan_kode != '00'" 

    enum status: {tetap:1, isidentil:2}

    #slugger
    extend FriendlyId
    friendly_id :nama_rekening, use: :slugged

    def kode_dan_nama_rekening
        "#{kode} - #{nama_rekening}"
    end

    def rekenig_lengkap
        "4.#{kode}.#{jenis_kode}.#{turunan_kode}"
    end

    def rekenig_lengkap_dan_nama
        "4.#{kode}.#{jenis_kode}.#{turunan_kode} - #{nama_rekening}"
    end
end

app/controllers/rekenings_controller.rb
class RekeningsController < ApplicationController
  before_action :set_rekening, only: [:show, :edit, :update, :destroy]
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper
  add_breadcrumb '<i class="ace-icon fa fa-home home-icon"></i> Home'.html_safe, :root_path
  add_breadcrumb ' Index Rekening'.html_safe, :rekenings_path
  # GET /rekenings
  # GET /rekenings.json
  def index
    rekening_scope = Rekening.all
    if params[:filter] != '' and params[:filter] != nil
      rekening_scope = rekening_scope.where("trim(upper(nama_rekening)) like trim(upper('%" + params[:filter] + "%'))")
    end
      if params[:filter_induk_rekening] != '' and params[:filter_induk_rekening] != nil
        rekening_scope = rekening_scope.where("kode = '" + params[:filter_induk_rekening] + "'")
      end
      if params[:filter_tahun_rekening] != '' and params[:filter_tahun_rekening] != nil
        rekening_scope = rekening_scope.where("tahun = " + params[:filter_tahun_rekening])
      end
    @rekening = smart_listing_create(:rekenings, rekening_scope, partial: "rekenings/listing", default_sort: {tahun: "desc", kode: "asc", jenis_kode: "asc", turunan_kode: 'asc'})
  end

  # GET /rekenings/1
  # GET /rekenings/1.json
  def show
    add_breadcrumb @rekening.nama_rekening.capitalize
  end

  # GET /rekenings/new
  def new
    add_breadcrumb 'Buat Baru'
    @rekening = Rekening.new
  end

  # GET /rekenings/1/edit
  def edit
  end

  # POST /rekenings
  # POST /rekenings.json
  def create
    params[:rekening][:tarif] = params[:rekening][:tarif].gsub('.', '').gsub(',', '.')
    @rekening = Rekening.new(rekening_params)
    respond_to do |format|
      if @rekening.save
        format.html { redirect_to @rekening, notice: 'Rekening berhasil tersimpan.' }
        format.json { render :show, status: :created, location: @rekening }
      else
        format.html { render :new }
        format.json { render json: @rekening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rekenings/1
  # PATCH/PUT /rekenings/1.json
  def update
    respond_to do |format|
      params[:rekening][:tarif] = params[:rekening][:tarif].gsub('.', '').gsub(',', '.')
      if @rekening.update(rekening_params)
        format.html { redirect_to @rekening, notice: 'Rekening berhasil tersimpan.' }
        format.json { render :show, status: :ok, location: @rekening }
      else
        format.html { render :edit }
        format.json { render json: @rekening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rekenings/1
  # DELETE /rekenings/1.json
  def destroy
    @rekening.destroy
    respond_to do |format|
      format.html { redirect_to rekenings_url, notice: 'Rekening berhasil terhapus.' }
      format.json { head :no_content }
    end
  end

  def update_rekening
    id = ''
    if params[:tahun_rekening] != ''
      id = params[:tahun_rekening]
    else
      id = 0
    end
    if params[:turunan] == 'true'
      if params[:status].present?
        @rekenings = Rekening.where("persen !=0 and persen is not null and jenis_kode != '00' and kode= '" + params[:kode] + "' and tahun = " + id + " and status=" + Rekening.statuses[params[:status]].to_s).order(kode: "asc", jenis_kode: "asc", turunan_kode: 'asc')
      else
        @rekenings = Rekening.where("persen !=0 and persen is not null and jenis_kode != '00' and kode= '" + params[:kode] + "' and tahun = " + id).order(kode: "asc", jenis_kode: "asc", turunan_kode: 'asc')
      end
    else
      @rekenings = Rekening.where("jenis_kode='00' and turunan_kode='00' and tahun = ?", id).order(kode: "asc", jenis_kode: "asc", turunan_kode: 'asc')
    end
    render json: @rekenings
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rekening
      @rekening = Rekening.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rekening_params
      params.require(:rekening).permit(:status, :kode, :jenis_kode, :turunan_kode, :tahun, :tarif, :persen, :nama_rekening, :filter, :filter_induk_rekening, :filter_tahun_rekening, :turunan)
    end
end

app/views/rekenings/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_for(rekening, :html => {:class => "form-horizontal", :role => "form"}) do |f| %>
      <%= render 'shared/error', error_form: rekening %>

      <div class="row">
          <div class="field">
            <div class="form-group">
              <%= f.label :tahun, class: "col-sm-2 control-label no-padding-right" %>
        <div class="col-md-1">
              <%= f.text_field :tahun, class: "form-control", validate: true, :maxlength => 4,  onkeypress: 'return event.charCode >= 48 && event.charCode <= 57' %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
          <div class="field">
            <div class="form-group">
              <%= f.label :Kode_rekening, class: "col-sm-2 control-label no-padding-right" %>
              <div class="col-md-3">
              <div class='input-group'>
                <span class="input-group-addon">4.</span>
                <%= f.text_field :kode, class: "form-control", validate: true, :maxlength => 4,  onkeypress: 'return event.charCode >= 48 && event.charCode <= 57' %>
                <span class="input-group-addon">.</span>
                <%= f.text_field :jenis_kode, class: "form-control", validate: true, :maxlength => 2,  onkeypress: 'return event.charCode >= 48 && event.charCode <= 57' %>
                <span class="input-group-addon">.</span>
                <%= f.text_field :turunan_kode, class: "form-control", validate: true, :maxlength => 2,  onkeypress: 'return event.charCode >= 48 && event.charCode <= 57' %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
          <div class="field">
            <div class="form-group">
              <%= f.label :nama_rekening, class: "col-sm-2 control-label no-padding-right" %>
        <div class="col-md-4">
              <%= f.text_field :nama_rekening, class: "form-control", validate: true %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
          <div class="field">
            <div class="form-group">
              <%= f.label :nilai_pasar, "Nilai", class: "col-sm-2 control-label no-padding-right" %>
              <div class="col-md-3">
              <div class='input-group'>
                <span class="input-group-addon">Rp.</span>
                  <%= f.text_field :tarif, class: "form-control money-left", validate: true, data: { role: 'money' } %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
          <div class="field">
            <div class="form-group">
              <%= f.label :tarif_persen, "Tarif", class: "col-sm-2 control-label no-padding-right" %>
            <div class="col-md-2">
              <div class='input-group'>
                <% rekening.persen = number_with_precision rekening.persen, precision: 2,  strip_insignificant_zeros: true, separator: '.', delimiter: ',' %>
                <%= f.text_field :persen, class: "form-control money-left", validate: true,  onkeypress: 'return event.charCode == 46 || (event.charCode >= 48 && event.charCode <= 57)', :maxlength => 3 %>
                <span class="input-group-addon">%</span>
              </div>
            </div>
          </div>
        </div>
      </div>
        <div class="row">
            <div class="field">
              <div class="form-group">
                <%= label_tag :status, nil, class: "col-sm-2 control-label no-padding-right" %>
                <div class="col-md-2">
                <%= f.select(:status, Rekening.statuses.keys.to_a.map { |w| [w.humanize, w] }, {include_blank:true}, {class: "form-control"}) %>
              </div>
            </div>
          </div>
        </div>
      <div class="clearfix form-actions">
        <div class="col-md-offset-3 col-md-9">
          <%= button_tag(type: 'submit', class: "btn btn-info") do %>
            <i class="ace-icon fa fa-check bigger-110"></i> Simpan
          <% end %>
          &nbsp; &nbsp; &nbsp;
          <%= link_to(raw('<i class="ace-icon fa fa-undo bigger-110"></i> kembali'), rekenings_path, class: "btn") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rekenings/_listing.html.erb
<% unless smart_listing.empty? %>
<div class="table-container">
  <table class="table table-striped table-bordered">
    <thead>
      <tr role="row">
        <th class="sorting"><%= smart_listing.sortable "Tahun", :tahun %></th>
        <th class="sorting">Kode Rekening</th>
        <th class="sorting">Nama Rekening</th>
        <th class="sorting">Tarif</th>
        <th class="sorting">Nilai</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% 
          counting = 1
      %>
      <% smart_listing.collection.each do |n| %>
              <% if counting.odd? %>
                  <tr role="row" class="odd">
              <% else %>
                <tr role="row" class="even">
              <% end %>
          <td><%= n.tahun %></td>
          <td><%= '4.' + n.kode + '.' + n.jenis_kode + '.' + n.turunan_kode %></td>
          <td><%= n.nama_rekening %></td>
          <td><%= number_with_precision n.persen, precision: 2,  strip_insignificant_zeros: true, separator: '.', delimiter: ',' %> %</td>
          <td style="text-align:right;">Rp. <%= humanized_money n.tarif %></td>
          <td>
              <div class="action-buttons">
                  <%= link_to(raw('<i class="ace-icon fa fa-search-plus bigger-130"></i>'), n, class:"blue") %>
                  <%= link_to(raw('<i class="ace-icon fa fa-pencil bigger-130"></i>'), edit_rekening_path(n), class:"green") %>
                  <%= link_to(raw('<i class="ace-icon fa fa-trash-o bigger-130"></i>'), n, method: :delete, data: { confirm: 'Anda yakin?' }, class:"red") %>
              </div>
          </td>
        </tr>
        <% counting += 1 %>
      <% end %>
    </tbody>
  </table>
</div>
<%= smart_listing.paginate  %>
<% else %>
<p> Data tidak ditemukan </p>
<% end %>

app/views/rekenings/edit.html.erb
<div class="page-header">
    <h1>Rekening
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Edit
        </small>
    </h1>
</div>

<%= render 'form', rekening: @rekening %>

app/views/rekenings/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h3 class="header smaller lighter blue">Index Rekening</h3>
    <div class="clearfix"></div>
	<div class="row">
		<div class="col-xs-12">
			<div class="pull-right tableTools-container">
				<div class="dt-buttons btn-overlap btn-group">
					<%= link_to(raw('<i class="ace-icon fa fa-plus icon-on-right bigger-110"></i> Tambah Rekening'), new_rekening_path, class: "dt-button buttons-collection buttons-colvis btn btn-success") %>
				</div>
			</div>
		</div>
	</div>
	<div class="table-header"> Tabel Daftar Rekening </div>
		<div id="dynamic-table_wrapper" class="dataTables_wrapper form-inline">
			<div class="row">
				<%= smart_listing_controls_for(:rekenings, {class: "form-inline text-right"}) do %>
				<div class="col-md-12">
					<div class="form-group">
						<div class="col-sm-12">
							<%= select_tag(:filter_tahun_rekening, options_from_collection_for_select(Rekening.select(:tahun).distinct, :tahun, :tahun), {prompt: ' -- Pilih Tahun Pajak -- ', class: "chosen-select  form-control", onchange:"$('.smart-listing-controls').submit();"}) %>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-12">
						<%= select_tag(:filter_induk_rekening, options_from_collection_for_select(Rekening.where("jenis_kode='000' and turunan_kode='000'"), :id, :nama_rekening), {prompt: ' -- Pilih induk Rekening -- ', class: "chosen-select  form-control", onchange:"$('.smart-listing-controls').submit();"}) %>
					</div>
					</div>
					<div class="form-group">
						<div class="input-group">
							<%= text_field_tag :filter, '', class: "search form-control", placeholder: "Cari berdasarkan nama...", autocomplete: :on, onchange:"$('.smart-listing-controls').submit();" %>
							<div class="input-group-btn">
								<button class="btn btn-primary no-border btn-sm" type="submit">
									<i class="ace-icon fa fa-search icon-on-right bigger-110"></i>
								</button>
							</div>
						</div>
					</div>
				</div>
				<% end %>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12">
					<%= smart_listing_render(:rekenings) %>
				</div>
			</div>
		</div>
	</div>
  </div>
</div>

app/views/rekenings/index.js.erb
<%= smart_listing_update :rekenings %>

app/views/rekenings/new.html.erb
<div class="page-header">
    <h1>Rekening
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Buat baru
        </small>
    </h1>
</div>

<%= render 'form', rekening: @rekening %>

app/views/rekenings/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="widget-box">
      <div class="widget-header widget-header-flat">
        <h4 class="widget-title smaller">Detail Rekening</h4>
        <div class="widget-toolbar">
          <%= link_to(raw('<i class="ace-icon fa fa-pencil align-center"></i> Edit'), edit_rekening_path(@rekening)) %> | 
          <%= link_to(raw('<i class="ace-icon fa fa-undo icon-only"></i> Kembali'), rekenings_path) %> |
          <%= link_to(raw('<i class="ace-icon fa fa-trash icon-only"></i> Hapus'), @rekening, method: :delete, data: { confirm: 'Ada yakin ingin menghapus data ini?' }) %>
        </div>
      </div>
      <div class="widget-body">
        <div class="widget-main">
          <div class="profile-user-info profile-user-info-striped">
            <div class="profile-info-row">
              <div class="profile-info-name"> <strong> Tahun Rekening </strong>
              </div>
              <div class="profile-info-value">
                <span class="editable editable-click"><%= @rekening.tahun %></span>
              </div>
            </div>
          </div>
          <div class="profile-user-info profile-user-info-striped">
            <div class="profile-info-row">
              <div class="profile-info-name"> <strong> Kode Rekening </strong>
              </div>
              <div class="profile-info-value">
                <span class="editable editable-click"><%= '4.' + @rekening.kode + '.' + @rekening.jenis_kode + '.' + @rekening.turunan_kode %></span>
              </div>
            </div>
          </div>
          <div class="profile-user-info profile-user-info-striped">
            <div class="profile-info-row">
              <div class="profile-info-name"> <strong> Nama Rekening </strong>
              </div>
              <div class="profile-info-value">
                <span class="editable editable-click"><%= @rekening.nama_rekening %></span>
              </div>
            </div>
          </div>
          <div class="profile-user-info profile-user-info-striped">
            <div class="profile-info-row">
              <div class="profile-info-name"> <strong> Tarif Rupiah </strong>
              </div>
              <div class="profile-info-value">
                <span class="editable editable-click">Rp. <%= humanized_money @rekening.tarif %></span>
              </div>
            </div>
          </div>
          <div class="profile-user-info profile-user-info-striped">
            <div class="profile-info-row">
              <div class="profile-info-name"> <strong> Tarif Persen </strong>
              </div>
              <div class="profile-info-value">
                <span class="editable editable-click"><%= number_with_precision @rekening.persen, precision: 2,  strip_insignificant_zeros: true, separator: '.', delimiter: ',' %>%</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>